name: Python pytest 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    service:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017 
  steps:
  - name: Git Checkout
    uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      # pip install -r requirements.txt
      pip install pytest pytest-cov pymongo
  - name: Test with pytest
    run: |
      # pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      pytest test.py --cov=com --cov-report=md
