name: Python pytest 
on: [push]
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  deployments: write
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017 
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install pytest pytest-cov pymongo
    - name: Build coverage file
      run: |
        pytest app/ --junitxml=pytest.xml --cov=app/ | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: pytest-coverage.txt
        junitxml-path: pytest.xml
